<a href="https://colab.research.google.com/github/imnotamr/Assignments/blob/main/NumpyAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
#1. Create a 2D Numpy array with shape (3, 3) containing random integers between 1 and 20.

ar= np.random.randint(low = 1, high = 20, size = (3,3))
print(ar)

[[19  3 17]
 [ 5  4 19]
 [ 6  9 16]]


In [14]:
#2. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values for each row

ar = np.random.randint(low = 1, high = 30, size = (5,5))
print("original array\n",ar)
print("max",ar.max(axis = 1))
print("min",ar.min(axis = 1))

original array
 [[18 17 13 10  2]
 [13  4 24 19 36]
 [27  4 22 13  4]
 [ 6 34 23 10  4]
 [36 36 36  1 11]]
max [18 36 27 34 36]
min [2 4 4 4 1]


In [18]:
#3. Write a NumPy program to create a random vector of size 10 and sort it.

ar = np.random.random(10)
print("original array\n",ar)
print("sorted array\n",np.sort(ar))


original array
 [0.48554233 0.75140336 0.08033891 0.060225   0.03791139 0.91314444
 0.26936208 0.51491263 0.85597066 0.3814899 ]
sorted array
 [0.03791139 0.060225   0.08033891 0.26936208 0.3814899  0.48554233
 0.51491263 0.75140336 0.85597066 0.91314444]


In [33]:
#4. Write a NumPy program to find the most frequent value in an array.
ar = np.random.randint(low=20 , high=50 , size=15)
frequency_dict = {}

for value in ar:
    if value in frequency_dict:
        frequency_dict[value] += 1
    else:
        frequency_dict[value] = 1

most_frequent_value = max(frequency_dict, key=frequency_dict.get)
print (ar)
print("most frequent value: ",most_frequent_value)



[26 24 30 33 45 33 30 39 25 46 35 21 29 48 37]
most frequent value:  30


In [46]:
#5. Replace all even numbers in the 2D array with 0.
arr = np.array([[1,2,3],[4,5,6]])
print("original array\n",arr)
arr[arr % 2 == 0] = 0
print("after replace\n",arr)

original array
 [[1 2 3]
 [4 5 6]]
after replace
 [[1 0 3]
 [0 5 0]]


In [52]:
#6. Apply the square root function to each element of the 1D array.
ar = np.array([1,16,100,4,49])
print("original array\n",ar)
print("square root of array",np.sqrt(ar))

original array
 [  1  16 100   4  49]
square root of array [ 1.  4. 10.  2.  7.]


In [57]:
arr = np.random.random((3,3))
print(arr)
mean = arr.mean()
print(mean)


[[0.62141505 0.41798417 0.07345925]
 [0.82412578 0.78922467 0.54867628]
 [0.67280076 0.40497797 0.41703354]]
0.5299663848454451


In [60]:
#7. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.
arr = np.random.random((3,3))
print("original array\n",arr)
print("mean of each row\n",arr.mean(axis = 1))
new_arr = arr - arr.mean(axis = 1)
print("subtracted array\n",new_arr)

original array
 [[0.98422159 0.23961125 0.27005625]
 [0.52908329 0.81704976 0.01603568]
 [0.82701821 0.21809471 0.05651543]]
mean of each row
 [0.49796303 0.45405624 0.36720945]
subtracted array
 [[ 0.48625856 -0.21444499 -0.0971532 ]
 [ 0.03112026  0.36299351 -0.35117377]
 [ 0.32905518 -0.23596153 -0.31069402]]


In [77]:
#8. Create a 1D array containing the first 20 odd numbers.
arr = np.arange(1,40,1)
print(arr,"\n")
odd_arr = arr[arr % 2 != 0]
print("the odd numbers",odd_arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39] 

the odd numbers [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [90]:
#9. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.
arr = np.random.random((5, 5))
print("original array\n ",arr)

sorted_arr = np.sort(arr, axis=0)
print("Sorted array\n",sorted_arr)

seclarval_arr = sorted_arr[-2, ::]
print("second largest values\n",seclarval_arr)

original array
  [[0.58349154 0.04966181 0.21837106 0.77812413 0.19691998]
 [0.51274776 0.24267944 0.03219948 0.00155586 0.65498568]
 [0.43174756 0.24845025 0.61066948 0.49227432 0.29480239]
 [0.75963059 0.80696602 0.82555252 0.4082628  0.73929034]
 [0.42824377 0.89794296 0.60003328 0.17526609 0.92952193]]
Sorted array
 [[0.42824377 0.04966181 0.03219948 0.00155586 0.19691998]
 [0.43174756 0.24267944 0.21837106 0.17526609 0.29480239]
 [0.51274776 0.24845025 0.60003328 0.4082628  0.65498568]
 [0.58349154 0.80696602 0.61066948 0.49227432 0.73929034]
 [0.75963059 0.89794296 0.82555252 0.77812413 0.92952193]]
second largest values
 [0.58349154 0.80696602 0.61066948 0.49227432 0.73929034]


In [95]:
#[I used the randint just to check the answer easily :) ]10. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

arr = np.random.randint(low = 1, high = 10, size = (4,4))
print(arr)
sum_arr = np.sum(arr , axis = 1)
print("the sum\n",sum_arr)

[[5 1 9 7]
 [5 9 2 2]
 [7 9 2 9]
 [7 7 6 7]]
the sum
 [22 18 27 27]
